/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BannerOperation: typeof import('./src/components/BannerOperation.vue')['default']
    BlogOperation: typeof import('./src/components/BlogOperation.vue')['default']
    BookOrder: typeof import('./src/components/BookOrder.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CategoryOperation: typeof import('./src/components/CategoryOperation.vue')['default']
    CodOperation: typeof import('./src/components/CodOperation.vue')['default']
    CollectionOperation: typeof import('./src/components/CollectionOperation.vue')['default']
    CouponOperation: typeof import('./src/components/CouponOperation.vue')['default']
    DeleteDailog: typeof import('./src/components/DeleteDailog.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    FacilityOperation: typeof import('./src/components/FacilityOperation.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PagesOperation: typeof import('./src/components/PagesOperation.vue')['default']
    PermissionOperations: typeof import('./src/components/PermissionOperations.vue')['default']
    ProductColor: typeof import('./src/components/ProductColor.vue')['default']
    ProductOperation: typeof import('./src/components/ProductOperation.vue')['default']
    ProductPrice: typeof import('./src/components/ProductPrice.vue')['default']
    ProductReviewOperation: typeof import('./src/components/ProductReviewOperation.vue')['default']
    PurchaseOperation: typeof import('./src/components/PurchaseOperation.vue')['default']
    RoleOperations: typeof import('./src/components/RoleOperations.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingOperation: typeof import('./src/components/SettingOperation.vue')['default']
    SocialMediaOperation: typeof import('./src/components/SocialMediaOperation.vue')['default']
    SubCategoryOperation: typeof import('./src/components/SubCategoryOperation.vue')['default']
    SupplierOperation: typeof import('./src/components/SupplierOperation.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UserOperations: typeof import('./src/components/UserOperations.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
    WebsiteOperations: typeof import('./src/components/websiteOperations.vue')['default']
  }
}
